# Generated by Django 6.0.1 on 2026-01-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="email_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Когда было отправлено письмо о достижении 100 просмотров",
                null=True,
                verbose_name="Дата отправки email о 100 просмотрах",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото для блога",
                null=True,
                upload_to="blog/preview",
                verbose_name="Превью",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="views_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Укажите количество просмотров", verbose_name="Количество просмотров"
            ),
        ),
    ]
