# Generated by Django 6.0.1 on 2026-01-14 10:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import catalog.models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите описание категории",
                max_length=2000,
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите описание товара",
                max_length=2000,
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Введите название категории",
                max_length=150,
                unique=True,
                verbose_name="Наименование категории",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=catalog.models.get_default_category_id,
                help_text="Введите категорию товара",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="products",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                help_text="Загрузите фото товара",
                null=True,
                upload_to="catalog/product_photo",
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Введите название товара",
                max_length=150,
                verbose_name="Наименование товара",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Укажите цену в рублях с копейками. Минимальная цена: 1 рубль",
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Цена должна быть больше нуля. Минимум 1 рубль"
                    )
                ],
                verbose_name="Цена за покупку (руб.)",
            ),
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите ваше имя",
                        max_length=150,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Имя должно содержать только буквы, пробелы или дефисы.",
                                regex="^[a-zA-Za-яА-ЯёЁ\\s\\-]+$",
                            ),
                            django.core.validators.MinLengthValidator(2, message="Имя слишком короткое"),
                        ],
                        verbose_name="Имя пользователя",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Введите контактный телефон",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Номер может содержать только цифры и символы +, -, (, )",
                                regex="^\\+?[\\d\\s\\-\\(\\)]+$",
                            ),
                            django.core.validators.MinLengthValidator(
                                10,
                                message="Номер слишком короткий. Введите минимум 10 цифр.",
                            ),
                        ],
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Введите ваше сообщение",
                        max_length=2000,
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="catalog_con_created_a7f1c4_idx"),
                    models.Index(fields=["name"], name="catalog_con_name_fb91fd_idx"),
                ],
            },
        ),
    ]
