# Generated by Django 6.0 on 2026-01-01 23:08

import catalog.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="descriptions",
            field=models.TextField(
                blank=True,
                help_text="Введите описание категории",
                max_length=2000,
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Введите название категории",
                max_length=150,
                unique=True,
                verbose_name="Наименование категории",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=catalog.models.get_default_category_id,
                help_text="Введите категорию товара",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="products",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="descriptions",
            field=models.TextField(
                blank=True,
                help_text="Введите описание товара",
                max_length=2000,
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Введите название товара",
                max_length=150,
                verbose_name="Наименование товара",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Укажите цену в рублях с копейками. Минимальная цена: 1 рубль",
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Цена должна быть больше нуля. Минимум 1 рубль"
                    )
                ],
                verbose_name="Цена за покупку (руб.)",
            ),
        ),
    ]
