# Generated by Django 6.0.1 on 2026-01-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_remove_category_descriptions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото товара",
                null=True,
                upload_to="catalog/product_photo",
                verbose_name="Фото",
            ),
        ),
    ]
