# Generated by Django 6.0 on 2026-01-02 23:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_category_descriptions_alter_category_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите ваше имя",
                        max_length=150,
                        verbose_name="Имя пользователя",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Введите контактный телефон",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Введите корректный номер телефона",
                                regex="^[\\d\\s\\-\\+\\(\\)]+$",
                            )
                        ],
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Введите ваше сообщение",
                        max_length=2000,
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="catalog_con_created_a7f1c4_idx"
                    ),
                    models.Index(fields=["name"], name="catalog_con_name_fb91fd_idx"),
                ],
            },
        ),
    ]
