# Generated by Django 6.0 on 2026-02-01 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=True, help_text="Отображать товар на сайте", verbose_name="Опубликован"),
        ),
        migrations.AlterField(
            model_name="product",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Укажите цену в рублях с копейками. Минимальная цена: 1 рубль",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Цена за покупку (руб.)",
            ),
        ),
    ]
