# Generated by Django 6.0 on 2026-01-05 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_contact"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="descriptions",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="descriptions",
            new_name="description",
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(
                help_text="Введите ваше имя",
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Имя должно содержать только буквы, пробелы или дефисы.",
                        regex="^[a-zA-Za-яА-ЯёЁ\\s\\-]+$",
                    ),
                    django.core.validators.MinLengthValidator(
                        2, message="Имя слишком короткое"
                    ),
                ],
                verbose_name="Имя пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(
                help_text="Введите контактный телефон",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер может содержать только цифры и символы +, -, (, )",
                        regex="^\\+?[\\d\\s\\-\\(\\)]+$",
                    ),
                    django.core.validators.MinLengthValidator(
                        10, message="Номер слишком короткий. Введите минимум 10 цифр."
                    ),
                ],
                verbose_name="Телефон",
            ),
        ),
    ]
