# Generated by Django 6.0.1 on 2026-02-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_is_published_alter_product_purchase_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='descriptions',
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, help_text='Укажите цену в рублях с копейками. Минимальная цена: 1 рубль', max_digits=10, verbose_name='Цена за покупку (руб.)'),
        ),
    ]
